In [2]:
import pandas as pd

data = pd.read_csv("complaints_fixed.csv")
data

,text,category,region,organization
0,ขอหน่วยงานที่เกี่ยวข้องวางท่อส่งน้ำสำหรับขยายเ...,น้ำ,สระบุรี,สปน.
1,ขอให้หน่วยงานที่เกี่ยวข้องดำเนินการแก้ไขปัญหาร...,อื่น ๆ,ทุกภูมิภาค,กต.
2,ขอให้ช่วยเหลือเยียวยาประชาชนที่ได้รับผลกระทบจา...,สาธารณภัย,สุพรรณบุรี,กษ.
3,ขอให้รัฐบาลทบทวนการแก้ไขปัญหาประชาคมกระเหรี่ยง...,ที่ดินทำกิน,เพชรบุรี,ทส.
4,ขอให้พิจารณาดำเนินการแก้ไขปัญหาการลักลอบเล่นพน...,อาชญากรรม ยาเสพติดและการพนัน,กรุงเทพมหานคร,ตร.
...,...,...,...,...
1952,ขอให้พิจารณากำกับดูแลและเร่งดำเนินการจัดทำร่าง...,การเมือง,ทุกภูมิภาค,สลค.
1953,ขอให้หน่วยงานที่เกี่ยวข้องบูรณาการการทำงานร่วม...,สวัสดิการ,ทุกภูมิภาค,กต.
1954,ขอให้หน่วยงานที่เกี่ยวข้องดำเนินการฟื้นฟูเศรษฐ...,เศรษฐกิจ การคลัง,ภาคตะวันออก,คค.
1955,ขอความอนุเคราะห์ให้จัดระบบประปาหมู่บ้าน ม.6 บ้...,น้ำ,เชียงใหม่,มท.
1956,ขอให้รัฐบาลทบทวนการแก้ไขปัญหาประชาคมกระเหรี่ยง...,ที่ดินทำกิน,เพชรบุรี,ทส.

In [3]:
data["text"]

0       ขอหน่วยงานที่เกี่ยวข้องวางท่อส่งน้ำสำหรับขยายเ...
1       ขอให้หน่วยงานที่เกี่ยวข้องดำเนินการแก้ไขปัญหาร...
2       ขอให้ช่วยเหลือเยียวยาประชาชนที่ได้รับผลกระทบจา...
3       ขอให้รัฐบาลทบทวนการแก้ไขปัญหาประชาคมกระเหรี่ยง...
4       ขอให้พิจารณาดำเนินการแก้ไขปัญหาการลักลอบเล่นพน...
                              ...
1952    ขอให้พิจารณากำกับดูแลและเร่งดำเนินการจัดทำร่าง...
1953    ขอให้หน่วยงานที่เกี่ยวข้องบูรณาการการทำงานร่วม...
1954    ขอให้หน่วยงานที่เกี่ยวข้องดำเนินการฟื้นฟูเศรษฐ...
1955    ขอความอนุเคราะห์ให้จัดระบบประปาหมู่บ้าน ม.6 บ้...
1956    ขอให้รัฐบาลทบทวนการแก้ไขปัญหาประชาคมกระเหรี่ยง...
Name: text, Length: 1957, dtype: object

## N-gram

In [4]:
!pip install newmm-tokenizer

Collecting newmm-tokenizer
  Downloading newmm_tokenizer-0.2.2-py3-none-any.whl (320 kB)
     ---------------------------------------- 0.0/320.6 kB ? eta -:--:--
     - -------------------------------------- 10.2/320.6 kB ? eta -:--:--
     --- --------------------------------- 30.7/320.6 kB 435.7 kB/s eta 0:00:01
     ---- -------------------------------- 41.0/320.6 kB 487.6 kB/s eta 0:00:01
     ---------------- --------------------- 143.4/320.6 kB 1.1 MB/s eta 0:00:01
     -------------------------------------- 320.6/320.6 kB 2.2 MB/s eta 0:00:00
Installing collected packages: newmm-tokenizer
Successfully installed newmm-tokenizer-0.2.2

In [5]:
from newmm_tokenizer.tokenizer import word_tokenize

text = data["text"].iloc[0]
text, repr(word_tokenize(text))

('ขอหน่วยงานที่เกี่ยวข้องวางท่อส่งน้ำสำหรับขยายเขตการจ่ายน้ำประปาไปยังพื้นที่บ้านตาลเสี้ยน หมู่ที่ ๖ ต.หนองแก อ.พระพุทธบาท จังหวัดสระบุรี เนื่องจากประสบปัญหาน้ำประปาในหมู่บ้านไม่เพียงพอในการอุปโภคบริโภค โดยที่ผ่านมาการประปาส่วนภูมิภาคได้ดำเนินโครงการสำรวจและขยายเขตการจ่ายน้ำประปาแล้ว แต่ยังไม่ได้วางท่อส่งน้ำและจุดสิ้นสุดในการวางท่อส่งน้ำอยู่ที่บริเวณถนนก่อนถึงหมู่บ้านดังกล่าว',
 "['ขอ', 'หน่วยงาน', 'ที่', 'เกี่ยวข้อง', 'วาง', 'ท่อ', 'ส่ง', 'น้ำ', 'สำหรับ', 'ขยาย', 'เขต', 'การ', 'จ่าย', 'น้ำประปา', 'ไป', 'ยัง', 'พื้นที่', 'บ้าน', 'ตาล', 'เสี้ยน', ' ', 'หมู่', 'ที่', ' ', '๖', ' ', 'ต.', 'หนอง', 'แก', ' ', 'อ.', 'พระพุทธบาท', ' ', 'จังหวัด', 'สระบุรี', ' ', 'เนื่องจาก', 'ประสบปัญหา', 'น้ำประปา', 'ใน', 'หมู่บ้าน', 'ไม่', 'เพียงพอ', 'ใน', 'การ', 'อุปโภค', 'บริโภค', ' ', 'โดย', 'ที่ผ่านมา', 'การประปาส่วนภูมิภาค', 'ได้', 'ดำเนิน', 'โครง', 'การสำรวจ', 'และ', 'ขยาย', 'เขต', 'การ', 'จ่าย', 'น้ำประปา', 'แล้ว', ' ', 'แต่', 'ยัง', 'ไม่', 'ได้', 'วาง', 'ท่อ', 'ส่ง', 'น้ำ', 'และ', 'จุดสิ้นสุด', 'ใน', 'การ', 'วาง', 'ท่อ', 'ส่ง', 'น้ำ', 'อยู่', 'ที่', 'บริเวณ', 'ถนน', 'ก่อน', 'ถึง', 'หมู่บ้าน', 'ดังกล่าว']")

## N-gram vectorization

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

# vectorizer = CountVectorizer()
vectorizer = CountVectorizer(tokenizer=word_tokenize)
# vectorizer = CountVectorizer(tokenizer=word_tokenize, ngram_range=(1, 2))
vectorizer.fit(data["text"])
len(vectorizer.vocabulary_)

d:\6510451000\machine-learning-mini-project\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

6498

In [8]:
repr(vectorizer.vocabulary_)[:100]

"{'ขอ': 800, 'หน่วยงาน': 4565, 'ที่': 2083, 'เกี่ยวข้อง': 5003, 'วาง': 3960, 'ท่อ': 2154, 'ส่ง': 4506"

In [9]:
vocabulary = vectorizer.vocabulary_.items()
vocabulary = sorted(vocabulary, key=lambda token_index: token_index[1])
vocabulary = [token for token, index in vocabulary]
print(repr(vocabulary[:10]))

['\n', ' ', '"', '%', '(', '(กข', '(กนช.)', '(กป', '(กพฐ.)', '(กยท.)']

In [10]:
vector = vectorizer.transform([text]).A[0]
text, repr(word_tokenize(text)), repr(vocabulary[:100]), repr(list(vector))[:100]

('ขอหน่วยงานที่เกี่ยวข้องวางท่อส่งน้ำสำหรับขยายเขตการจ่ายน้ำประปาไปยังพื้นที่บ้านตาลเสี้ยน หมู่ที่ ๖ ต.หนองแก อ.พระพุทธบาท จังหวัดสระบุรี เนื่องจากประสบปัญหาน้ำประปาในหมู่บ้านไม่เพียงพอในการอุปโภคบริโภค โดยที่ผ่านมาการประปาส่วนภูมิภาคได้ดำเนินโครงการสำรวจและขยายเขตการจ่ายน้ำประปาแล้ว แต่ยังไม่ได้วางท่อส่งน้ำและจุดสิ้นสุดในการวางท่อส่งน้ำอยู่ที่บริเวณถนนก่อนถึงหมู่บ้านดังกล่าว',
 "['ขอ', 'หน่วยงาน', 'ที่', 'เกี่ยวข้อง', 'วาง', 'ท่อ', 'ส่ง', 'น้ำ', 'สำหรับ', 'ขยาย', 'เขต', 'การ', 'จ่าย', 'น้ำประปา', 'ไป', 'ยัง', 'พื้นที่', 'บ้าน', 'ตาล', 'เสี้ยน', ' ', 'หมู่', 'ที่', ' ', '๖', ' ', 'ต.', 'หนอง', 'แก', ' ', 'อ.', 'พระพุทธบาท', ' ', 'จังหวัด', 'สระบุรี', ' ', 'เนื่องจาก', 'ประสบปัญหา', 'น้ำประปา', 'ใน', 'หมู่บ้าน', 'ไม่', 'เพียงพอ', 'ใน', 'การ', 'อุปโภค', 'บริโภค', ' ', 'โดย', 'ที่ผ่านมา', 'การประปาส่วนภูมิภาค', 'ได้', 'ดำเนิน', 'โครง', 'การสำรวจ', 'และ', 'ขยาย', 'เขต', 'การ', 'จ่าย', 'น้ำประปา', 'แล้ว', ' ', 'แต่', 'ยัง', 'ไม่', 'ได้', 'วาง', 'ท่อ', 'ส่ง', 'น้ำ', 'และ', 'จุดสิ้นสุด', 'ใน', 'การ', 'วาง', 'ท่อ', 'ส่ง', 'น้ำ', 'อยู่', 'ที่', 'บริเวณ', 'ถนน', 'ก่อน', 'ถึง', 'หมู่บ้าน', 'ดังกล่าว']",
 '[\'\\n\', \' \', \'"\', \'%\', \'(\', \'(กข\', \'(กนช.)\', \'(กป\', \'(กพฐ.)\', \'(กยท.)\', \'(คทช.)\', \'(งบ\', \'(ช.\', \'(นส.\', \'(ปชด.)\', \'(ภ.\', \'(วลพ.)\', \'(ส\', \'(สคทช.)\', \'(สพฐ\', \'(อ\', \')\', \')(\', \'+\', \',\', \'-\', \'.\', \'.)\', \'..\', \'..)\', \'...\', \'....\', \'....(\', \'.ค.\', \'.นรม\', \'.มค.\', \'.ย\', \'/\', \'/คน/\', \'0\', \'005\', \'1\', \'1,000,000\', \'10\', \'100\', \'100,000\', \'1069\', \'11\', \'115\', \'12\', \'1200\', \'130\', \'14\', \'15\', \'19\', \'2\', \'2.3\', \'2.5\', \'20\', \'20.00\', \'200,000\', \'2000\', \'2019\', \'2022\', \'205.26\', \'2094\', \'22\', \'2496\', \'25\', \'2559\', \'2560\', \'2561\', \'2562\', \'2564\', \'26\', \'28\', \'29\', \'3\', \'31\', \'32\', \'33\', \'3312\', \'359\', \'37\', \'3800\', \'4\', \'4.0\', \'41\', \'5\', \'50\', \'6\', \'6.5\', \'61\', \'62\', \'63\', \'64\', \'7\', \'85\', \'8798\', \'9\']',
 '[0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ')

In [11]:
counts = pd.DataFrame([vector], columns=vocabulary)
counts

,\n,,"""",%,(,(กข,(กนช.),(กป,(กพฐ.),(กยท.),...,"๙,๐๐๐",๙.๔๑,๙๐๐,๙๗,๙๗๐,–,“,“(,“โคะงุ,”
0,0,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
pd.Series(vector, index=vocabulary).sort_values(ascending=False).head(20)

            8
การ         4
ส่ง         3
น้ำ         3
วาง         3
ที่         3
ใน          3
ท่อ         3
น้ำประปา    3
ได้         2
ขยาย        2
ไม่         2
เขต         2
ยัง         2
และ         2
จ่าย        2
หมู่บ้าน    2
ไป          1
สระบุรี     1
จังหวัด     1
dtype: int64

In [13]:
pd.DataFrame(vectorizer.transform(data["text"]).A, columns=vocabulary)

,\n,,"""",%,(,(กข,(กนช.),(กป,(กพฐ.),(กยท.),...,"๙,๐๐๐",๙.๔๑,๙๐๐,๙๗,๙๗๐,–,“,“(,“โคะงุ,”
0,0,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,13,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,22,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1952,0,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1953,0,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1954,0,23,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1955,0,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1956,0,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0